---
name: Nginx Proxy Manager - With Stream
version: dev
slug: nginxproxymanagerstream
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/Shambala001/addon-nginx-proxy-manager
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:81]
init: false
arch:
  - amd64
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
  8843/tcp: 8843
ports_description:
  80/tcp: HTTP Entrance port
  81/tcp: Proxy management web interface
  443/tcp: HTTPS/SSL Entrance port
  8843/tcp: Extra stream port
map:
  - ssl:rw
  - backup:rw
backup_exclude:
  - "*/logs"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
